apiVersion: v1
kind: Secret
metadata:
    name: secret-mysql
    namespace: database
stringData:
    password: ENC[AES256_GCM,data:pwIjSxluJ73elL/qzV7P8R7LlQTRs8r51g==,iv:oWsSqjKyKukKKb3vejIR9Gf9Z/w+SOwIrGER7yKnrNM=,tag:rsq5QnhWq4Z6x/ok7Dmoag==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-10-15T16:59:24Z"
    mac: ENC[AES256_GCM,data:rKOf4pSv6aKcMPW0+/ugCZQkm/m+xNyWhnZqv1voOWmS5YbvX81ayuSR0XFKiIEJ/nykawnDtkDlPbVuXp9Zwyxiaxldnaa1iRU2qEUOXYSP22zOO8JfOynLHhi5oFtcDhzfNkusJ/MUvqkZuyXkwb1SQXCK4aAVoNjN4muOtiA=,iv:0P8xNGK//GA0VRbk/KBvJS9B8I1RQHp7VfV11XMsNjk=,tag:aT7XYC+ZklYM2n8jITQCpA==,type:str]
    pgp:
        - created_at: "2023-10-15T16:59:24Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQGMA1vin1z9i8ivAQwAsGkxcNOncv8dPGzPinSUZQ7raNcuBrFy+qi72S6rfPjh
            FWSHR5xmiartRVk4tD0rJMwhClD+XVo4+eAnYQ+jA56C4oyQeSOUKXTl/9sEb9NR
            9JcK3A581tcM3+6IPGXJ3VMYxPbX6UE1nUk5qHQouWQI8CvsMKKfBnEFy54f+qj5
            lluVDtQsv9HRN9VjQBTvyRqTrA5Xwr6CxvXqFRN2AI5KnEV58tEHX12nU7rfNkay
            36BBtkKv694RUo8Esq32nDKbzkK4lOHz3oycd8t5w964tznYlqWo0Upfy+lxmEKQ
            3GNzG1ldNKlCC3H8mW+d1TWK/ICSEQfGPVKZBToaV1MgYOS06Of9FwzDDasZfHMI
            RTGbzuEZfU04Es8UIsO/C+muuH3znSMtX0aAZu1C/CUdjurgs/9CFWGAreaGfnTx
            kTgwrgGg/cF1I8WvBJ/a0y1hkq9lkTAQB3eqEOtQ/MY2GOkcfunurMAmqlYKXfQE
            ai1MoYUR6Spf6jp7UDUn0lwB+BZdHWo30//6brhNZdm89BpdU0665mDnx0MkOok9
            iX4rWhQZ0CtPprxBJRxVZDYA1Vv7A3kI/9OSnzx14N5Hj1yjxq0vTF/b2Q70K3PG
            /yA+Z+0zEi1b20ypLw==
            =aCoX
            -----END PGP MESSAGE-----
          fp: E9BCC10882DBCBCE
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
